name: Expo updates

on:
  push:
    branches:
      - production
      - preview
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v3

      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:ci

      - name: 🚀 Submit update
        run: eas update -p all --auto --channel ${{ github.ref_name }}
